---
name: forca-react-prod
services:
  app:
    container_name: forca-react-prod-c
    image: forca-react-prod-i:2.0.2
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8029:80"
# docker compose -f docker-compose.prod.yml build
# docker image tag forca-react-prod-i:2.0.2 silveira42/forca-react:2.0.2
# docker image tag forca-react-prod-i:2.0.2 silveira42/forca-react:latest
# docker push silveira42/forca-react:2.0.2
# docker push silveira42/forca-react:latest
