---
name: forca-react-prod
services:
  app:
    container_name: forca-react-prod-c
    image: forca-react-prod-i:2.0
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
        - "8025:80"

# docker image tag forca-react-prod-i:2.0 silveira42/forca-react:2.0
# docker image tag forca-react-prod-i:2.0 silveira42/forca-react:latest
# docker push silveira42/forca-react:2.0
# docker push silveira42/forca-react:latest
